name: Device
run-name: Home Station pipelines for device
on: [push]
jobs:
  build_firmware:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq build-essential cmake gcc-arm-none-eabi ninja-build openocd
      - name: Build firmware
        run: |
          cd device
          cmake -GNinja -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DCMAKE_BUILD_TYPE=debug -Bbuild
          cmake --build build
      - name: Archive linker map file
        uses: actions/upload-artifact@v4
        with:
          name: linker-map-file
          path: build/output.map
  build_and_run_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq build-essential cmake gcc lcov ninja-build
      - name: Build and run test suite
        run: |
          cd device
          cmake -GNinja -DCMAKE_BUILD_TYPE=test -Bbuild
          cmake --build build
          ctest -V --test-dir build
