name: Gateway
run-name: Home station pipelines for gateway
on:
  push:
    branches:
      - main
jobs:
  build_test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -yq make python3 python3-venv
      - name: Configure virtual environment and run test suite
        run: |
          cd gateway
          make test
